name: deployment
on: workflow_dispatch
jobs:
  ci:
    runs-on: [self-hosted, mac-runner]
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            ./app/*
          sparse-checkout-cone-mode: false

      - name: build dockerfile
        run: |
          cd app
          docker build -t nikhilsonawane2jpg/k8s-webapp:v1 .
          docker push nikhilsonawane2jpg/k8s-webapp:v1

  cd: 
    needs: ci
    runs-on: [self-hosted, linux-runner]
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            yaml
          sparse-checkout-cone-mode: false
      - name: up database
        run: |
          
          kubectl apply -f yaml/configmap.yaml
          kubectl apply -f yaml/pv.yaml
          kubectl apply -f yaml/secret.yaml
          kubectl apply -f yaml/ingress.yaml
          kubectl apply -f yaml/statefulset.yaml
      - name: wait for db
        run: sleep 60
      - name: run app
        run: kubectl apply -f yaml/app-deployment.yaml
      
